### ISSUE TITLE
Update axios package requirements

### ISSUE THREAD

**Issue by Yaswanth-Tippireddy** [mvanroon/react-native-axios-jwt#21]
Hi, Can you please bump up the specs in Axios-requirements

**Comment by mvanroon** [comment]
Done

**Comment by Yaswanth-Tippireddy** [comment]
Thanks @mvanroon, but i think you forgot to update the version in package.json.

**Comment by mvanroon** [comment]
@Yaswanth-Tippireddy https://github.com/mvanroon/react-native-axios-jwt/commit/6b7ea03d0f699214eaef27967230af0c1c2b3c58

**Comment by mvanroon** [comment]
You're right. My apologies.
